### ISSUE TITLE
MVX Issues

### ISSUE THREAD

**Issue by hipsofjw** [jeffqchen/10DIN2VGA#1]
Hello!

I recently bought a couple of Extron MVX matrix switchers and so dove into making your adapters. This is the first one I've made and am having issues. When I go directly into my JVC TM-H150CG or into the Retrotink 5X through an RGB2SCART box, all is good. But I'm getting sync issues through the MVX to the JVC and no image at all through the MVX and RGB2SCART to the Retrotink 5X. I've configured the jumpers for RGBS mode and haven't closed the other ones. I also have the SMD components installed for CSYNC.

Maybe I've messed something up soldering, but I'm not seeing any issues visually or through my multimeter. If you could give me some advice, let me know!

Thanks for these projects by the way. I've had fun building them so far.

**Comment by jeffqchen** [comment]
When using an MVX, remember the sync it outputs is TTL 5V, not  the consumer 1Vpp. You need to add a 470 to 1K resistor on the sync line to attenuate the sync signal. Otherwise the 5X might keep resetting itself, and you risk damage the JVC if it doesn't support TTL sync.

**Comment by hipsofjw** [comment]
The JVC can handle TTL signals fine, but I also have a 470 to 1k resistor on the sync line from the MVX to the JVC anyway. Since neither the JVC or the 5X recognize the 10DIN2VGA sync through the MVX but do directly, I think the problem right now is that the MVX is having a problem with the sync from the 10DIN2VGA. Do you have any idea why this could happen? For science, I tried using my other MVX and had the same issue.

**Comment by jeffqchen** [comment]
I just tested the one I have in hand.

Saturn to MVX to 5X. It worked without any issue.

The sync resistor used inside the dongle was 470 ohm. The resistor used on the MVX to 5X side was also 470 ohm.

Please check the VGA cables you are using.

**Comment by hipsofjw** [comment]
Thanks for getting back to me. VGA cables are good. New and shielded. Did a continuity check and all the pins are wired.

Must be my bad SMD soldering. I'm new to it. I'm going to start fresh with a new board tomorrow and give it whirl. Too difficult to move the little things around now that I have the big components on.

Thanks again!

**Comment by jeffqchen** [comment]
No problem.

One thing is that I'm using an MVX 88. If yours is a different model, there might be some kind of hidden nuance.
